- dockerfiles/README.md
- pattern-1/is-deployment.yaml
> Change docker tag name

- README.md
Fix root readme to reflect teh new changes made for NFS server configurations.
This PR fixes the incorrect readme.
N/A
N/A
N/
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> Fix readme to reflect the new changes made for NFS server configurations.

- README.md
- is-with-analytics/README.md
- is/README.md
> Update README documentation with proper instructions and descriptions.
> Update README documentation

- is-with-analytics/README.md
- is-with-analytics/scripts/README.md
- is/README.md
- is/scripts/README.md
> Update README.md documentation of WSO2 Identity Server 5.6.x Kubernetes resources.
> Update README.md documentation of WSO2 Identity Server 5.6.x Kubernetes resources.
> Update README.md documentation of WSO2 Identity Server 5.6.x Kubernetes resources

- README.md
- helm/is-with-analytics/README.md
- helm/is/README.md
- is-with-analytics/README.md
- is-with-analytics/scripts/README.md
- is/README.md
- is/scripts/README.md
> Update README.md documentation of Kubernetes and Helm resources. This fixes https://github.com/wso2/kubernetes-is/issues/47.
> Update README.md documentation of Kubernetes and Helm resources.
> Update README.md documentation of Kubernetes and Helm resources

- helm/is-with-analytics/README.md
> Update readme documentation
> Update readme documentation
> Delete unwanted instructions for location paths in <HELM_HOME>/is-with-analytics-conf/values.yaml
> N/A
> N/A
> N/A
> N/A
> N/A
>N/A
- Unit tests 
> N/A
- Integration tests
> N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> N/A
> N/A
> N/A
> N/A
> Update Helm is-with-analytics readme documentation

- README.md
- is-with-analytics/README.md
- is-with-analytics/is-analytics/identity-server-analytics-1-deployment.yaml
- is-with-analytics/is-analytics/identity-server-analytics-2-deployment.yaml
- is-with-analytics/is-analytics/identity-server-analytics-volume-claims.yaml
- is-with-analytics/scripts/README.md
- is-with-analytics/volumes/persistent-volumes.yaml
- is/README.md
- is/scripts/README.md
> Refines Kubernetes resources for WSO2 Identity Server 5.5.x. This improves the README.md documentation along with necessary instructions to introduce additional configurations and artifacts where necessary. Plus, it removes the unnecessary persistence of `<DAS_HOME>/conf/analytics` folder.
> Refines Kubernetes resources for WSO2 Identity Server 5.5.x.
> This improves the README.md documentation along with necessary instructions to introduce additional configurations and artifacts where necessary. Plus, it removes the unnecessary persistence of `<DAS_HOME>/conf/analytics` folder.
> Refine Kubernetes resources for WSO2 Identity Server 5.5.x

- helm/is/README.md
> Update the README.md

- CHANGELOG.md
- ManageArtifacts.md
- ManageConfigurations.md
- README.md
- advance/is-with-analytics/README.md
- advance/is-with-analytics/scripts/README.md
- advance/is/README.md
- advance/is/scripts/README.md
> Improve README and change log documentation.
> Improve README and change log documentation
> Improve README and change log documentation

- README.md
> Fix incorrect README link provided in the main README.
> Fix incorrect README link provided in the main README
> Fix incorrect README link

- advanced/helm/is-with-analytics/README.md
- advanced/helm/is/README.md
Change the path of HELM_HOME according to the folder structure.
> Change the helm path in README.md

- README.md
- advanced/is-with-analytics/scripts/deploy.sh
- advanced/is/identity-server-deployment.yaml
- advanced/is/scripts/deploy.sh
> Adjust sed command to work with Darwin and Linux platforms.
> Adjust sed command to work with Darwin and Linux platforms
> Adjust sed command to work with Darwin and Linux platforms

- advanced/helm/is/is/templates/NOTES.txt
> Update product documentation link

- advanced/helm/is-with-analytics/is-with-analytics/templates/identity-server-conf-datasources.yaml
- advanced/helm/is-with-analytics/is-with-analytics/templates/identity-server-conf-identity.yaml
- advanced/helm/is/is/templates/NOTES.txt
> Fixes the documentation link and Config map details in Helm charts.

- CHANGELOG.md
- README.md
Update release version in Readme.md and CHANGELOG.md
> Update release version in Readme.md and CHANGELOG.md

- advanced/is/README.md
> Adding recommended approaches to address some of the requirements which comes while creating production deployments
> Adding information on advance deployment options to README

- advanced/helm/is-with-analytics/is-with-analytics/confs/is/conf/datasources/master-datasources.xml
- advanced/helm/is-with-analytics/is-with-analytics/confs/is/conf/user-mgt.xml
- advanced/helm/is-with-analytics/is-with-analytics/templates/NOTES.txt
- advanced/helm/is/is/confs/datasources/master-datasources.xml
- advanced/helm/is/is/confs/user-mgt.xml
> Resolves #125
> Remove 'dataSource' from primary user store configs
> Remove 'dataSource' from primary user store configs

- CHANGELOG.md
- advanced/helm/is-pattern-1/README.md
- advanced/helm/is-pattern-1/confs/carbon.xml
- advanced/helm/is-pattern-1/templates/identity-server-conf.yaml
- advanced/helm/is-pattern-1/templates/identity-server-ingress.yaml
- advanced/helm/is-pattern-2/README.md
- advanced/helm/is-pattern-2/confs/is/conf/carbon.xml
- advanced/helm/is-pattern-2/templates/identity-server-conf.yaml
- advanced/helm/is-pattern-2/templates/identity-server-dashboard-ingress.yaml
- advanced/helm/is-pattern-2/templates/identity-server-ingress.yaml
> Resolves #160 
> Parameterize ingress hostnames to support multiple deployments
> Parameterize ingress hostname

- advanced/helm/is-pattern-1/README.md
- advanced/helm/is-pattern-1/values.yaml
- advanced/helm/is-pattern-2/README.md
- advanced/helm/is-pattern-2/values.yaml
> Resolves #158  
> Add comments to the values.yaml files explaining the purposes of each value
> Update Helm chart documentation to enable centralized logging
> Add documentation to configurations

- advanced/helm/is-pattern-1/confs/axis2/axis2.xml
- advanced/helm/is-pattern-1/templates/_helpers.tpl
- advanced/helm/is-pattern-1/templates/identity-server-conf-axis2.yaml
- advanced/helm/is-pattern-1/templates/identity-server-ingress.yaml
- advanced/helm/is-pattern-1/templates/identity-server-service.yaml
- advanced/helm/is-pattern-2/README.md
- advanced/helm/is-pattern-2/confs/is/conf/axis2/axis2.xml
- advanced/helm/is-pattern-2/confs/is/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-AuthenticationData.xml
- advanced/helm/is-pattern-2/confs/is/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-RoleData.xml
- advanced/helm/is-pattern-2/confs/is/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-SessionData.xml
- advanced/helm/is-pattern-2/confs/is/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-UserData.xml
- advanced/helm/is-pattern-2/templates/identity-server-analytics-dashboard-deployment.yaml
- advanced/helm/is-pattern-2/templates/identity-server-analytics-dashboard-service.yaml
- advanced/helm/is-pattern-2/templates/identity-server-analytics-worker-deployment.yaml
- advanced/helm/is-pattern-2/templates/identity-server-analytics-worker-service.yaml
- advanced/helm/is-pattern-2/templates/identity-server-conf-axis2.yaml
- advanced/helm/is-pattern-2/templates/identity-server-conf-event-publishers.yaml
- advanced/helm/is-pattern-2/templates/identity-server-dashboard-ingress.yaml
- advanced/helm/is-pattern-2/templates/identity-server-ingress.yaml
- advanced/helm/is-pattern-2/templates/identity-server-service.yaml
> Resolves #157
> Formalize naming conventions
> Formalize naming conventions for Helm resources

- advanced/helm/is-pattern-1/README.md
- advanced/helm/is-pattern-1/templates/is/identity-server-prometheus-blackbox-serviceMonitor.yaml
- advanced/helm/is-pattern-1/templates/is/identity-server-prometheus-serviceMonitor.yaml
- advanced/helm/is-pattern-1/values.yaml
- advanced/helm/is-pattern-2/templates/analytics-dashboard/identity-server-analytics-dashboard-prometheus-blackbox-monitoring.yaml
- advanced/helm/is-pattern-2/templates/identity-server-prometheus-jmx-monitoring.yaml
- advanced/helm/is-pattern-2/templates/is/identity-server-is-prometheus-blackbox-monitoring.yaml
- advanced/helm/is-pattern-2/values.yaml
> fixes #172 
>Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
> Add Unique IDs for Service monitors

- advanced/helm/is-pattern-2/templates/analytics-dashboard/identity-server-analytics-dashboard-deployment.yaml
- advanced/helm/is-pattern-2/templates/analytics-worker/identity-server-analytics-worker-1-deployment.yaml
- advanced/helm/is-pattern-2/templates/analytics-worker/identity-server-analytics-worker-2-deployment.yaml
fixes #174 
> Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
> Fix Image pull secret issue

- advanced/helm/is-pattern-2/confs/logstash/c4/logstash.conf
- advanced/helm/is-pattern-2/confs/logstash/c5/logstash.conf
If logstash starts after some logs are written, they are not parsed. To avoid this, we add to parameters.
- sincedb_path - maintain the last parsed logline
- start_position - Start parsing the file from the beginning.
> Update logstash configuration

- CHANGELOG.md
- README.md
> Prepare resources for v5.8.0.3 release
> Prepare resources for v5.8.0.3 release
> Prepare resources for v5.8.0.3 release

- CHANGELOG.md
- README.md
Add changelog for release 5.9.0.1
> Add changelog for release 5.9.0.1

- advanced/is-pattern-1/templates/is/identity-server-conf.yaml
- advanced/is-pattern-2/templates/is/identity-server-conf.yaml
Add the namespace element to identity-server-conf.yaml.
> Add namespace for configmap identity-server-conf.yaml

- advanced/is-pattern-1/README.md
- advanced/is-pattern-2/README.md
Remove NGINX version requirement from README.md
> Remove NGINX version requirement from README.md

- simple/create.sh
- simple/deployment-scripts/wso2is-latest.sh
- simple/funcs
> Add new WSO2 Software License to the deployment script
> Add  License view logic

- advanced/is-pattern-1/templates/_helpers.tpl
> This PR fixes pattern name in named templates for WSO2 Identity Server Helm resources.
> Fix Pattern Name in Named Templates
> [v5.10.x] Fix Pattern Name in Named Templates

- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
- advanced/is-pattern-1/templates/logstash/wso2is-pattern-1-c4-logstash-conf.yaml
- advanced/is-pattern-1/values.yaml
> This PR fixes $subject. Thus, fixes https://github.com/wso2/kubernetes-is/issues/247.
> Update Logstash version
> Helm version: `3.1.2`
> GKE based Kubernetes Server version: `1.15`+, Git Version: `v1.15.12-gke.2`
> WSO2 product images available at WSO2 Private Docker Registry were used
> [v5.10.x] Upgrade Logstash Version - 2020-08-06

- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-bin.yaml
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
> This PR addresses $subject fixing the linked issue.
> Fix SSLHandshakeException during Membership Scheme Initialization
> See [discussion](https://stackoverflow.com/questions/60790118/java-kubernetes-client-sslhandshakeexception-extension-5-should-not-be-present)
> Helm version: `3.2.4`
> GKE based Kubernetes Server version: `1.16`+, Git Version: `v1.16.13-gke.1`
> [v5.10.x] Fix SSLHandshakeException during Membership Scheme Initialization

- advanced/is-pattern-1/README.md
> This addresses $subject with appropriate directions to the [official WSO2 container guide](https://github.com/wso2/container-guide). This closes the linked issues.
> Update IAM Helm chart README documentation
> [v5.10.x] Update IAM Helm Chart README Documentation

- advanced/is-pattern-1/Chart.yaml
- advanced/is-pattern-1/README.md
- advanced/is-pattern-1/requirements.yaml
- advanced/is-pattern-1/templates/NOTES.txt
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-conf.yaml
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
- advanced/is-pattern-1/values.yaml
This PR includes the Helm resources create scripts for WSO2 IAM version 5.11.0 deployment in Kubernetes. 
https://github.com/wso2/kubernetes-is/issues/266
> Add Helm resources create scripts for IAM 5.11

- CHANGELOG.md
Update the WSO2 IAM 5.11.0 release date in the Change log
> Update the change log with release date

- advanced/is-pattern-1/templates/_helpers.tpl
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
Use update 2 images when subscription is enabled.
> Use update 2 images when subscription is enabled.

- advanced/is-pattern-1/templates/_helpers.tpl
- advanced/is-pattern-1/templates/prometheus/wso2is-pattern-1-identity-server-prometheus-serviceMonitor.yaml
Fix image name and tag generation to use custom registry
> Fix image name and tag generation to use custom registry

- CHANGELOG.md
- README.md
- advanced/databases/mysql-is/Chart.yaml
- advanced/is-pattern-1/Chart.yaml
- advanced/is-pattern-1/README.md
- advanced/is-pattern-1/requirements.yaml
> Prepare for relase 5.11.0.2

- CHANGELOG.md
- README.md
- advanced/databases/mysql-is/Chart.yaml
- advanced/is-pattern-1/Chart.yaml
- advanced/is-pattern-1/README.md
- advanced/is-pattern-1/requirements.yaml
- advanced/is-pattern-1/templates/_helpers.tpl
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
- advanced/is-pattern-1/templates/prometheus/wso2is-pattern-1-identity-server-prometheus-serviceMonitor.yaml
> Merge 5.11.x into master

- advanced/databases/mysql-is/requirements.yaml
Change mysql dependency to bitnami repo
> Change mysql dependency to bitnami repo

- advanced/is-pattern-1/templates/_helpers.tpl
> Fix template issue

- CHANGELOG.md
- advanced/databases/mysql-is/Chart.yaml
- advanced/is-pattern-1/Chart.yaml
- advanced/is-pattern-1/README.md
- advanced/is-pattern-1/requirements.yaml
As described in the title this PR is to update the changelog for v5.11.0.3 for the new release version. 
https://github.com/wso2/kubernetes-is/issues/288
> Update changelog for v5.11.0.3 and update the latest release version

- CHANGELOG.md
- advanced/databases/mysql-is/Chart.yaml
- advanced/is-pattern-1/Chart.yaml
- advanced/is-pattern-1/README.md
- advanced/is-pattern-1/requirements.yaml
- advanced/is-pattern-1/templates/_helpers.tpl
> Merge 5.11.0.x with Master

- advanced/databases/mysql-is/requirements.yaml
> Use MySQL from WSO2 repo

- advanced/is-pattern-1/values.yaml
Alter the IS pod resources to fit with machines with average resources.
> Alter the IS pod resources.

- advanced/is-pattern-1/values.yaml
Optimise the IAM pod resoruces.
> Optimise the IAM pod resoruces.

- advanced/is-pattern-1/Chart.yaml
Update 5.11.0 latest helm chart version of 5.11.0-4
> Update 5.11.0 latest Helm chart version

- README.md
- advanced/is-pattern-1/requirements.yaml
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-conf.yaml
- advanced/is-pattern-1/values.yaml
> This PR performs $subject.
> Merge `master` branch to `5.11.x`
> Merge `master` branch to `5.11.x`

- advanced/is-pattern-1/templates/wso2is-pattern-1-rbac.yaml
> This performs $subject fixing https://github.com/wso2/kubernetes-is/issues/313.
> Upgrade API version of Kubernetes RoleBinding resource
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1"}
> Upgrade API version of Kubernetes RoleBinding resource

- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-ingress.yaml
- advanced/is-pattern-1/values.yaml
> This performs $subject. Fixes https://github.com/wso2/kubernetes-is/issues/312.
> Upgrade the API version of Kubernetes Ingress resource
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1"}
> Upgrade the API version of Kubernetes Ingress resource

- CHANGELOG.md
- CONTRIBUTING.md
- advanced/is-pattern-1/README.md
> This performs $subject.
> Update documentation for `v5.11.0.5` release
> Update documentation for `v5.11.0.5` release

- CHANGELOG.md
> Update change log for `v5.11.0.5` release

- CHANGELOG.md
- CONTRIBUTING.md
- advanced/databases/mysql-is/Chart.yaml
- advanced/databases/mysql-is/requirements.yaml
- advanced/is-pattern-1/Chart.yaml
- advanced/is-pattern-1/README.md
- advanced/is-pattern-1/requirements.yaml
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-conf.yaml
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-ingress.yaml
- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
- advanced/is-pattern-1/templates/wso2is-pattern-1-rbac.yaml
- advanced/is-pattern-1/values.yaml
- simple/README.md
- simple/create.sh
- simple/deployment-scripts/wso2is-ga.sh
- simple/deployment-scripts/wso2is-latest.sh
- simple/funcs
- simple/funcs4opensource
- simple/is-k8s/identity-server-deployment.yaml
> Merge `5.11.x` branch to `master` - 2021-11-25.
> Merge `5.11.x` branch to `master` - 2021-11-25
> Merge `5.11.x` branch to `master`

- CHANGELOG.md
- CONTRIBUTING.md
- simple/README.md
- simple/create.sh
- simple/deployment-scripts/wso2is-latest.sh
- simple/eulatxt
- simple/funcs
- simple/funcs4opensource
- simple/mysql-k8s/mysql-conf-db.yaml
> Simplified setup scripts for WSO2 IAM version 6.1.0
> Addressed changes related to 6.1.0 distribution and db script changes.
> * https://github.com/wso2/product-is/issues/15493
> Simplified setup scripts for WSO2 IAM version 6.1.0

- advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-bin.yaml
> Fix error message for clarity

- CHANGELOG.md
- Chart.yaml
- README.md
- confs/deployment.toml
- templates/deployment.yaml
- values.yaml
This will take the changes in the current master to 7.0.x
The below two PRs are captured
- https://github.com/wso2/kubernetes-is/pull/335
- https://github.com/wso2/kubernetes-is/pull/336
It will also bump the version to 7.0.0-2
> Update 7.0.x with improvements from master and update tag

- templates/deployment.yaml
- values.yaml
> $subject
- https://github.com/wso2-enterprise/asgardeo-product/issues/29474
> [main] Update app armor config

- CHANGELOG.md
- Chart.yaml
- README.md
This PR updates the Helm chart version and README.
- Bumped `Chart.yaml` version
- Updated `README.md` with latest information
> Update helm chart version to 7.1.0-2

- README.md
- templates/deployment.yaml
- templates/pv.yaml
- templates/route.yaml
- values.yaml
> This PR contains the OpenShift route support with few addition parameters to support for OpenShift deployments.
> Add configs to support OpenShift
