dockerfiles/is/Dockerfile
dockerfiles/is/change_ownership.sh
dockerfiles/is/init_carbon.sh

This PR add support for copying files to dropins and lib folder to the default distribution. If there are any files in /home/wso2user/wso2is-5.5.0-lib or /home/wso2user/wso2is-5.5.0-dropins folder, those files will be copied to repository/components/lib and repository/components/dropins folder respectively.
Provide support for adding customizations through lib and dropins folder.
N/A
N/A
Add support for copying customized jars to libs and dropins folder
N/A
N/A
N/A
N/A
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
N/A
N/A
N/A
N/A
N/A

Add support for libs and dropins copying

---

advanced/helm/is-with-analytics/is-with-analytics/templates/identity-server-analytics-dashboard-deployment.yaml
advanced/helm/is-with-analytics/is-with-analytics/templates/identity-server-analytics-worker-deployment.yaml
advanced/helm/is-with-analytics/is-with-analytics/templates/identity-server-deployment.yaml
advanced/helm/is/is/templates/identity-server-deployment.yaml

Add conditional use of imagePullCredentials when using WSO2 private docker registry in helm charts.

Ignore imagePullCredentials when using public docker images

---

advanced/helm/is-pattern-1/templates/identity-server-deployment.yaml
advanced/helm/is-pattern-2/templates/identity-server-analytics-dashboard-deployment.yaml
advanced/helm/is-pattern-2/templates/identity-server-analytics-worker-deployment.yaml
advanced/helm/is-pattern-2/templates/identity-server-deployment.yaml

- It should be possible to choose if each image is using a third party docker registry rather than deciding as a whole. This way I would be able to use wso2 images while using an image from a private registry for one deployment.
- I should be able to use an image name without a tag since configuring spinnaker requires not having the tag.

Adding option to use image with no tag when using third party registry

---

advanced/helm/is-pattern-1/requirements.yaml
advanced/helm/is-pattern-1/templates/identity-server-deployment.yaml
advanced/helm/is-pattern-2/requirements.yaml
advanced/helm/is-pattern-2/templates/identity-server-analytics-dashboard-deployment.yaml
advanced/helm/is-pattern-2/templates/identity-server-analytics-worker-deployment.yaml
advanced/helm/is-pattern-2/templates/identity-server-deployment.yaml

When using the charts in CI/CD pipeline, not all images will come from one registry. Some might be from WSO2 docker registry while some might be from another private registry. Therefore it should be possible to plugin external secrets when pulling images from other registries.

Parameterize secrets for each deployment

---

advanced/helm/is-pattern-1/README.md
advanced/helm/is-pattern-1/templates/identity-server-ingress.yaml
advanced/helm/is-pattern-2/README.md
advanced/helm/is-pattern-2/templates/identity-server-ingress.yaml

Host name `<RELEASE_NAME>-wso2is` can be too long and confusing. Instead the release name itself could be used for the ingress host name.

Remove "wso2is" from ingress host name

---

advanced/helm/is-pattern-1/templates/is/identity-server-prometheus-blackbox-serviceMonitor.yaml

Use fully qualified name to identify service since the blackbox exporter might be in a different namespace than the service.

Use fully qualified  service name

---

advanced/helm/is-pattern-1/README.md
advanced/helm/is-pattern-2/README.md

> Add WSO2 helm chart prerequisite in documentation

Add WSO2 helm chart prerequisite in documentation

---

advanced/helm/is-pattern-1/templates/identity-server-conf-entrypoint.yaml
advanced/helm/is-pattern-1/templates/is/identity-server-deployment.yaml
advanced/helm/is-pattern-2/templates/identity-server-conf-entrypoint.yaml
advanced/helm/is-pattern-2/templates/is/identity-server-deployment.yaml

> Resolves #182  
> Fix empty value provided to "localMemberHost" in clustering configurations

Fix empty value provided to localMemberHost in clustering configurations

---

advanced/helm/is-pattern-1/README.md
advanced/helm/is-pattern-2/README.md

- Fix a broken link to Kubernetes clusters setup that is no longer available in the Kubernetes documentation.
- Change incorrect references to Enterprise Integrator.
- Change incorrect reference to `wso2ei` in default chart values.

Fix broken links and incorrect references to Enterprise Integrator

---

README.md

Fix broken links to quick start guides
- simple/Readme.md
- advanced/is-pattern-1/README.md
- advanced/is-pattern-2/README.md

Fix broken links to quick start guides

---

advanced/is-pattern-1/templates/identity-server-ingress.yaml
advanced/is-pattern-2/templates/identity-server-dashboard-ingress.yaml
advanced/is-pattern-2/templates/identity-server-ingress.yaml

The current implementation of the NGINX ingress resources does not work with the NGINX versions later than 0.22.0 (#198 ). This PR introduces the following changes to add support for this.
- Add annotation `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` to force the backend protocol to be HTTPS.
- Remove annotation `nginx.ingress.kubernetes.io/ssl-passthrough: "true"`

Use backend protocol HTTPS and disable SSL-passthrough for ingress

---

advanced/databases/mysql-is/requirements.yaml
advanced/is-pattern-1/requirements.yaml

This ended up being a fairly easy fix.
- Updated NFS server provisioner and MySQL requirements
Closes #195
Closing #195
Update to newer requirements that support K8s 1.16
#195
Support for Kubernetes 1.16
N/A - no changes to deployment procedures
N/A - does not affect certification
N/A - Existing tests should be sufficient
wso2/docker-is#202

Support for Kubernetes 1.16, Closes #195

---

advanced/databases/mysql-is/values.yaml
advanced/is-pattern-1/Chart.yaml
advanced/is-pattern-1/requirements.yaml
advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-volume-claims.yaml
advanced/is-pattern-1/values.yaml

> This PR performs $subject fixing https://github.com/wso2/kubernetes-is/issues/242. Furthermore, it adds the necessary configurations fixing https://github.com/wso2/kubernetes-is/issues/243.
> Avoid Packaging the NFS Server Provisioner
> Helm version: 3.1.2
> GKE based Kubernetes Server version: 1.14+, Git Version: `v1.14.10-gke.27`
> WSO2 Private Docker Registry images were utilized

[v5.10.x] Avoid Packaging the NFS Server Provisioner

---

advanced/is-pattern-1/README.md
advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
advanced/is-pattern-1/values.yaml

> This PR performs $subject thus fixing the linked issue.
> Allocate memory for JVM heap
> Helm version: `3.2.4`
> GKE based Kubernetes Server version: `1.15`+, Git Version: `v1.15.12-gke.2`
> Product Docker images from WSO2 Private Docker Registry were used

[v5.10.x] Allocate Memory for JVM Heap

---

advanced/is-pattern-1/README.md
advanced/is-pattern-1/templates/NOTES.txt
advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-conf.yaml
advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-ingress.yaml
advanced/is-pattern-1/values.yaml

> This PR performs $subject, thus closing the linked issue.
> Add input option to set Ingress class and annotations
> Helm version: `3.2.4`
> GKE based Kubernetes Server version: `1.15`+, Git Version: `v1.15.12-gke.2`
> Product Docker images from WSO2 organization in DockerHub

[v5.10.x] Add Input Option to Set Ingress Class and Annotations

---

advanced/databases/mysql-is/requirements.yaml

> This PR fixes $subject, thus closing the linked issue.
> Upgrade Base Stable MySQL Helm Chart - 2020-08-21
> Helm version: `3.2.4`
> GKE based Kubernetes Server version: `1.15`+, Git Version: `v1.15.12-gke.2`
> Product Docker images from WSO2 organization in DockerHub

[v5.10.x] Upgrade Base Stable MySQL Helm Chart - 2020-08-21

---

advanced/is-pattern-1/README.md
simple/README.md
simple/create.sh
simple/deployment-scripts/wso2is-ga.sh
simple/deployment-scripts/wso2is-latest.sh
simple/funcs
simple/funcs4opensource
simple/is-k8s/identity-server-deployment.yaml

Purpose
This will prevent special characters in the base64 encoded output to affect the sed command by removing in favor of using the kubctl CLI tool to generate the secret. Additionally, if the k8s file name variable was updated it would break on the removal of the .bak file. As well as the docker image tag structure has diverted from GA and subscription images. Introduced a variable to allow for each script to declare which version of the image to use.
Goals
make the script more resilient
Samples
my subscription password has special chars (?$) which resulted in a (/) in the base64 encoding.

remove sed for base64 encoded strings. improve script resilience

---

advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-conf.yaml

> nginx is proxying the https id_token auth and needs to omit the port for endpoint URLs
> User reported [issue](https://github.com/wso2/product-is/issues/10645)

Update base_path to the server hostname

---

advanced/databases/mysql-is/Chart.yaml
advanced/is-pattern-1/Chart.yaml
advanced/is-pattern-1/requirements.yaml
advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml
advanced/is-pattern-1/values.yaml

> This performs $subject and adds a Kubernetes startup probe fixing https://github.com/wso2/kubernetes-is/issues/230.
> Add Kubernetes startup probe to address Identity Server startup
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1"}

Evaluate Startup Probe for WSO2 Identity Server Workload

---

advanced/is-pattern-1/templates/is/wso2is-pattern-1-identity-server-bin.yaml

Following error was thrown during server startup in the cluster due to incompatibility issues in the latest JDK 11. 
```
ERROR {Events.Framework} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.identity.application.authenticator.fido [266]
Unresolved requirement: Import-Package: org.wso2.carbon.identity.application.authenticator.fido2.core; version="5.3.30.1"
-> Export-Package: org.wso2.carbon.identity.application.authenticator.fido2.core; bundle-symbolic-name="org.wso2.carbon.identity.application.authenticator.fido2"; bundle-version="5.3.30.2"; version="5.3.30.2"; uses:="com.fasterxml.jackson.core,org.wso2.carbon.identity.application.authentication.framework.exception,org.wso2.carbon.identity.application.authentication.framework.model,o …
```

Fix server startup issue in the cluster

---

README.md
templates/deployment.yaml
values.yaml

Enable AppArmor by default and provide the option to disable it through an if-condition.
- Implemented an if-condition to allow AppArmor to be disabled when needed.
- Added a note in the README to inform users about the AppArmor configuration and how to disable it.  
- Ensures that AppArmor is enabled by default, preventing unnecessary restrictions on containers unless explicitly enabled.

If-Condition to disable AppArmor

---

confs/deployment.toml
values.yaml

Add support for proxyPort configuration through the values.yaml
This will facilitate users to easily customize the proxy port during helm installation
A requirement to customize the proxy port arises when installing the helm chart in Rancher K3s. 
- https://github.com/wso2/product-is/issues/23152

Add support for proxyPort configuration

---

CHANGELOG.md
Chart.yaml
README.md
confs/deployment.toml
confs/secret-conf.properties
templates/secret-provider-class.yaml
values.yaml

- This PR introduces several improvements and adjustments to the Helm chart to support WSO2 Identity Server 7.1.0 and align with basic use cases.
- https://github.com/wso2/product-is/issues/23379
- Ensure compatibility with WSO2 Identity Server 7.1.0.
- Improve user onboarding via self-registration support.
- Align keystore formats with current standards.
- Enhance the documentation for easier setup and deployment.
- Made external keystore mandatory: Required for secure internal and external communications in B2B scenarios.
- Added user_self_registration.callback_url to deployment.toml: Enables self-registration functionality.
- Updated keystore files to .p12 format: Standardizes keystore usage across internal, primary, TLS, and truststores.
- Updated image tags and build version to …

Make Helm chart compatible with WSO2 Identity Server 7.1.0

---

README.md
values.yaml

> This PR sets the default value of externalJKS to false in the Helm chart, ensuring that the Identity Server uses its internal keystore configuration unless explicitly overridden.
> Updated values.yaml to set externalJKS: false
> Updated keystore file names to default wso2carbon.p12
> Updated Readme by removing mandatory keystore generation part

Make externalJKS false by default 

---

README.md
templates/deployment.yaml
values.yaml

> Add OpenShift support for IS helm charts
> Users should be able to deploy Identity Server in OpenShift using helm charts
> 1. runAsUser: If you are using arbitrary UIDs, you can disable runAsUser by setting deployment.securityContext.runAsUser.enabled=false
> 2. seLinux Support: If you need SELinux support, you can enable it by setting deployment.securityContext.seLinux.enabled=true
> 3. AppArmor Support: If you need AppArmor disabled, you can do so by setting deployment.apparmor.enabled=false
> 4. ConfigMap Access: If your runtime user doesn't have execute access to ConfigMaps, you can fix it by setting deployment.entrypoint.defaultMode=0457

Add OpenShift support for IS helm chart

---

README.md
values.yaml

This PR sets the default value of `externalJKS` to `false` in the Helm chart, ensuring that the Identity Server uses its internal keystore configuration unless explicitly overridden.
- Updated `values.yaml` to set `externalJKS: false`
- Updated keystore file names to default `wso2carbon.p12`
- Updated README by removing the mandatory keystore generation section

Make externalJKS false by default
